name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies and build frontend
      run: |
        cd boredjoke
        npm ci 
        npm run build
        
    - name: Setup Node.js for backend
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies for backend
      run: |
        cd backend
        npm ci
